#POST http://localhost:3000/api/groups


### 그룹 수정 요청 (PUT)
PUT http://localhost:3000/api/groups/2
Content-Type: application/json

{
    "password": "second456",
    "name": "Updated tester2",
    "imageUrl": "http://example.com/new-image.jpg",
    "isPublic": false,
    "introduction": "Updated group introduction."
}

### 다른 그룹 수정 요청 (PUT)
PUT http://localhost:3000/api/groups/1
Content-Type: application/json

{
    "password": "second456",
    "name": "Updated tester2",
    "imageUrl": "http://example.com/new-image.jpg",
    "isPublic": false,
    "introduction": "Updated group introduction."
}

### 삭제
DELETE http://localhost:3000/api/groups/2
Content-Type: application/json

{
  "password": "second456" // 사용자가 입력한 비밀번호
}