###게시글 등록
POST http://localhost:3000/api/groups/4/posts
Content-Type: application/json

{
	"nickname": "Book",
	"title": "test 2",
	"content": "test 2",
	"postPassword": "password456",
	"groupPassword": "password456",
	"imageUrl": "http://example.com/images/books.jpg",
	"tags": [ "book", "like" ],
	"location": "bookclub",
	"moment": "2024-09-30",
	"isPublic": true
}


###게시글 조회 latest, mostCommented, mostLiked
GET http://localhost:3000/api/groups/4/posts?page=1&pageSize=10&sortBy=lastest&keyword=test&isPublic=true


###게시글 수정
PUT http://localhost:3000/api/posts/1
Content-Type: application/json

{
    "nickname": "updatedNickname",
    "title": "updatedTitle",
    "content": "updatedContent",
    "postPassword": "password456",
    "imageUrl": "updatedImageUrl",
    "tags": ["updatedTag1", "updatedTag2"],
    "location": "updatedLocation",
    "moment": "2024-03-01",
    "isPublic": false
}


###게시글 삭제
DELETE http://localhost:3000/api/posts/1
Content-Type: application/json

{
	"postPassword":"password456"
}